# Shell variables
# Generated by 'wal'
wallpaper='sea.jpg'

# Special
background='#f0f5f3'
foreground='#24645f'
cursor='#24645f'

# Colors
color0='#f0f5f3'
color1='#3D7482'
color2='#6F8C91'
color3='#59838A'
color4='#657D84'
color5='#4F7A84'
color6='#759AA6'
color7='#b6cfd7'
color8='#7f9096'
color9='#3D7482'
color10='#6F8C91'
color11='#59838A'
color12='#657D84'
color13='#4F7A84'
color14='#759AA6'
color15='#24645f'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
